import '../styles/globals.css'

import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import type { JSX, ReactNode } from 'react'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

type Props = {
  children: ReactNode
}

export default function RootLayout({ children }: Readonly<Props>): JSX.Element {
  return (
    <html lang="en">
      <body className={`${fontSans.variable} font-sans antialiased`}>{children}</body>
    </html>
  )
}
