@baseUrl = http://localhost:3000
@jwtToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ3dTQweXBpa215bHFvaGg1andxeGJzaTQiLCJpYXQiOjE5MjA1MTQ1MzV9.jyIUrbCLoNjQnhX8FzzN7nk6GqIx_MIkiI6z-KTOZZE
@firstGroupId = adsiiktu8legs3hrbdi62qla
@newGroupId = {{createGroup.response.body.id}}
@firstUserId = is0k2tosseuislm4niylbuye
@secondUserId = wu40ypikmylqohh5jwqxbsi4
@thirdUserId = ez68vex4lvlpq8w7sncq4h2i
@fourthUserId = jr9loitvk8i2r562qg3jau4x
@fifthUserId = gu1sji4idpd9qnmkn2wvwdoq
@firstGroupTransactionId = mqywrmwz4dfo4tpsqzjaa7a0

# @name healthCheck
GET {{baseUrl}}/health-check

###

# @name getGroups
GET {{baseUrl}}/groups
Authorization: Bearer {{jwtToken}}

###

# @name getGroupById
GET {{baseUrl}}/groups/{{firstGroupId}}
Authorization: Bearer {{jwtToken}}

###

# @name createGroup
POST {{baseUrl}}/groups
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "name": "Group test",
  "description": "Group test description",
  "currency": "BRL"
}

###

# @name joinGroup
POST {{baseUrl}}/groups/{{firstGroupId}}/join-group
Authorization: Bearer {{jwtToken}}

###

# @name leaveGroup
POST {{baseUrl}}/groups/{{firstGroupId}}/leave-group
Authorization: Bearer {{jwtToken}}

###

# @name removeGroupMember
POST {{baseUrl}}/groups/{{firstGroupId}}/remove-group-member
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "memberId": "{{secondUserId}}"
}

###

# @name updateGroup
PATCH {{baseUrl}}/groups/{{firstGroupId}}
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "name": "Group test updated",
  "currency": "USD"
}

###

# @name deleteGroup
DELETE {{baseUrl}}/groups/{{newGroupId}}
Authorization: Bearer {{jwtToken}}

###

# @name getGroupTransactionsByGroupId
GET {{baseUrl}}/groups/{{firstGroupId}}/transactions?page=1&per-page=20&order=date&dir=desc
Authorization: Bearer {{jwtToken}}

###

# @name getGroupTransactionById
GET {{baseUrl}}/groups/{{firstGroupId}}/transactions/{{firstGroupTransactionId}}
Authorization: Bearer {{jwtToken}}

###

# @name createGroupTransaction
POST {{baseUrl}}/groups/{{firstGroupId}}/transactions
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "name": "Test transaction",
  "amount": 10000,
  "payerMemberId": "{{firstUserId}}",
  "participants": [
    {
      "memberId": "{{firstUserId}}",
      "amount": 2000
    },
    {
      "memberId": "{{secondUserId}}",
      "amount": 2000
    },
    {
      "memberId": "{{thirdUserId}}",
      "amount": 2000
    },
    {
      "memberId": "{{fourthUserId}}",
      "amount": 2000
    },
    {
      "memberId": "{{fifthUserId}}",
      "amount": 2000
    }
  ],
  "date": "2024-01-01"
}

###

# @name updateGroupTransaction
PATCH {{baseUrl}}/groups/{{firstGroupId}}/transactions/{{firstGroupTransactionId}}
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "name": "Test transaction",
  "amount": 5000,
  "payerMemberId": "{{firstUserId}}",
  "participants": [
    {
      "memberId": "{{firstUserId}}",
      "amount": 1000
    },
    {
      "memberId": "{{secondUserId}}",
      "amount": 1000
    },
    {
      "memberId": "{{thirdUserId}}",
      "amount": 1000
    },
    {
      "memberId": "{{fourthUserId}}",
      "amount": 1000
    },
    {
      "memberId": "{{fifthUserId}}",
      "amount": 1000
    }
  ],
  "date": "2024-01-01"
}

###

# @name deleteGroupTransaction
DELETE {{baseUrl}}/groups/{{firstGroupId}}/transactions/{{firstGroupTransactionId}}
Authorization: Bearer {{jwtToken}}

###

# @name getUserProfile
GET {{baseUrl}}/users/profile
Authorization: Bearer {{jwtToken}}
