services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      - divisio
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - divisio
    volumes:
      - redis:/data

  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.local
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - REDIS_URL=redis://redis:6379
      - WEB_URL=http://web:3001
    ports:
      - 3000:3000
    networks:
      - divisio

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    restart: unless-stopped
    depends_on:
      - server
    environment:
      - PORT=3001
      - SERVER_URL=http://server:3000
    ports:
      - 3001:3001
    networks:
      - divisio

networks:
  divisio:
    driver: bridge

volumes:
  postgres:
  redis:
