services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      - divisio
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - divisio
    volumes:
      - redis:/data

  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.docker
      - .env
    ports:
      - 3000:3000
    networks:
      - divisio

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        - APP_ENV
        - SERVER_PORT
        - WEB_PORT
        - JWT_SECRET
        - DATABASE_URL
        - REDIS_URL
        - SERVER_URL
        - WEB_URL
        - GOOGLE_OAUTH_CLIENT_ID
        - GOOGLE_CLIENT_SECRET
        - GOOGLE_OAUTH_REDIRECT_URL
    restart: unless-stopped
    depends_on:
      - server
    env_file:
      - .env.docker
      - .env
    ports:
      - 3001:3001
    networks:
      - divisio

networks:
  divisio:
    driver: bridge

volumes:
  postgres:
  redis:
