/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios'
import type { AxiosRequestConfig, AxiosResponse } from 'axios'
import type { GetGroups200, GetGroupsGroupId200 } from './api.schemas'

export const getGroups = () => {
  /**
   * Get groups by user
   * @summary Get groups
   */
  const getGroups = <TData = AxiosResponse<GetGroups200>>(
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.get('http://localhost:3000/groups', options)
  }
  /**
   * Get group by id
   * @summary Get group
   */
  const getGroupsGroupId = <TData = AxiosResponse<GetGroupsGroupId200>>(
    groupId: string,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.get(`http://localhost:3000/groups/${groupId}`, options)
  }
  return { getGroups, getGroupsGroupId }
}
export type GetGroupsResult = AxiosResponse<GetGroups200>
export type GetGroupsGroupIdResult = AxiosResponse<GetGroupsGroupId200>
