/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios'
import type { AxiosRequestConfig, AxiosResponse } from 'axios'
import type { PostSessionsRefresh200, PostSessionsRefreshBody } from './api.schemas'

export const getSessions = () => {
  /**
   * Returns a new JWT token
   * @summary Refresh token
   */
  const postSessionsRefresh = <TData = AxiosResponse<PostSessionsRefresh200>>(
    postSessionsRefreshBody: PostSessionsRefreshBody,
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.post('http://localhost:3000/sessions/refresh', postSessionsRefreshBody, options)
  }
  return { postSessionsRefresh }
}
export type PostSessionsRefreshResult = AxiosResponse<PostSessionsRefresh200>
