/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios'
import type { AxiosRequestConfig, AxiosResponse } from 'axios'
import type { GetUsersProfile200 } from './api.schemas'

export const getUsers = () => {
  /**
   * Get user profile by JWT token
   * @summary Get user profile
   */
  const getUsersProfile = <TData = AxiosResponse<GetUsersProfile200>>(
    options?: AxiosRequestConfig
  ): Promise<TData> => {
    return axios.get('http://localhost:3000/users/profile', options)
  }
  return { getUsersProfile }
}
export type GetUsersProfileResult = AxiosResponse<GetUsersProfile200>
