name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint code
        run: pnpm lint

      - name: Build contracts
        run: pnpm build:contracts

      - name: Build app
        run: pnpm build

      - name: Setup database
        run: docker compose up -d && sleep 2

      - name: Run tests
        run: pnpm test

      - name: Stop containers
        if: always()
        run: docker compose down

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Create domain for server app
        run: railway service server && railway environment fair-pact-pr-$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }') && railway domain
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Create domain for client app
        run: railway service client && railway environment fair-pact-pr-$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }') && railway domain
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
