name: Create PR Domain

on:
  pull_request:
    branches: [main]

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy server app
        run: railway link -p fair-pact -s server -e fair-pact-pr-$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }') && railway deploy --ci
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}

      - name: Deploy client app
        run: railway link -p fair-pact -s client -e fair-pact-pr-$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }') && railway deploy --ci
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}

      - name: Create domain for server app
        run: railway link -p fair-pact -s server -e fair-pact-pr-$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }') && railway domain && railway variables --set "CLIENT_URL=https://server-fair-pact-pr-$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }').up.railway.app" --set "GOOGLE_OAUTH_REDIRECT_URL=https://server-fair-pact-pr-$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }').up.railway.app/sessions/oauth/google"
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}

      - name: Create domain for client app
        run: railway link -p fair-pact -s client -e fair-pact-pr-$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }') && railway domain && railway variables --set "VITE_SERVER_URL=https://server-fair-pact-pr-$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }').up.railway.app"
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
