name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint code
        run: pnpm lint:ci

      - name: Build shared
        run: pnpm build:shared

      - name: Run tests
        run: pnpm test

      - name: Install Railway
        if: github.event_name == 'pull_request'
        run: npm i -g @railway/cli

      - name: Extract PR Number
        id: pr_number
        if: github.event_name == 'pull_request'
        run: echo "::set-output name=number::$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')"

      - name: Create domain for server app
        if: github.event_name == 'pull_request'
        run: |
          railway link -t workspace -p divisio -s server -e divisio-pr-${{ steps.pr_number.outputs.number }} &&
          railway variables --set "APP_ENV=staging" \
                            --set "JWT_SECRET=secret" &&
          railway domain -p 3000

      - name: Create domain for web app
        if: github.event_name == 'pull_request'
        run: |
          railway link -t workspace -p divisio -s web -e divisio-pr-${{ steps.pr_number.outputs.number }} &&
          railway variables --set "APP_ENV=staging" &&
          railway domain -p 3001

      - name: Prepare Postgres env
        if: github.event_name == 'pull_request'
        run: |
          railway link -t workspace -p divisio -s postgres -e divisio-pr-${{ steps.pr_number.outputs.number }} &&
          railway variables -k >> .env &&
          sed -i '/^DATABASE_URL=/d; s/^DATABASE_PUBLIC_URL=/DATABASE_URL=/'

      - name: Prepare Redis env
        if: github.event_name == 'pull_request'
        run: |
          railway link -t workspace -p divisio -s redis -e divisio-pr-${{ steps.pr_number.outputs.number }} &&
          railway variables -k >> .env &&
          sed -i '/^REDIS_URL=/d; s/^REDIS_PUBLIC_URL=/REDIS_URL=/' .env

      - name: Seed database
        if: github.event_name == 'pull_request'
        run: cat .env && pnpm db:migrate:ci && pnpm db:seed

      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarcloud-github-action@v4
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
